<script setup lang="ts">
import { ref } from 'vue';
import { ElMessageBox } from 'element-plus';
import { useAuthStore } from '../../stores/auth';
import { useWorkspaceStore } from '../../stores/workspace';
import { downloadText } from '../../lib/files';
defineProps<{studentsOnly:boolean}>();
const auth=useAuthStore();const workspace=useWorkspaceStore();
const legacyFile=ref<File>();const legacyChecked=ref(false);
async function chooseLegacy(event:Event){legacyFile.value=(event.target as HTMLInputElement).files?.[0];legacyChecked.value=false;}
async function migrate(dryRun:boolean){if(!legacyFile.value)return;if(!dryRun&&!await ElMessageBox.confirm('仅迁移到空班级，确认导入旧版数据？','迁移旧数据').then(()=>true).catch(()=>false))return;await run(async()=>{const value=await auth.api.importLegacy(workspace.classId,legacyFile.value,dryRun);legacyChecked.value=dryRun;if(!dryRun)await workspace.reloadReferences();return value;});}
const busy=ref(false);const error=ref('');const result=ref('');const studentFile=ref<File>();const backupFile=ref<File>();const validated=ref(false);const strategy=ref<'skip'|'create'>('skip');const mode=ref<'merge'|'replace'>('merge');
function selectFile(event:Event,kind:'student'|'backup'){const file=(event.target as HTMLInputElement).files?.[0];if(kind==='student')studentFile.value=file;else{backupFile.value=file;validated.value=false;}result.value='';}
async function run(action:()=>Promise<unknown>){if(busy.value)return;busy.value=true;error.value='';result.value='';try{const value=await action();if(value!==undefined)result.value=JSON.stringify(value,null,2);}catch(cause){error.value=workspace.message(cause);}finally{busy.value=false;}}
async function importStudents(dryRun:boolean){if(!studentFile.value)return;await run(async()=>{const value=await auth.api.uploadStudents(workspace.classId,studentFile.value,dryRun,strategy.value);if(!dryRun)await workspace.reloadReferences();return value;});}
async function validate(){if(!backupFile.value)return;validated.value=false;await run(async()=>{const value=await auth.api.validateBackup(workspace.classId,backupFile.value);validated.value=true;return value;});}
async function restore(){if(!backupFile.value||!validated.value)return;try{await ElMessageBox.prompt(`输入“${workspace.currentClass?.name}”确认${mode.value==='replace'?'替换当前班级数据':'合并备份数据'}。`,'恢复备份',{inputValidator:value=>value===workspace.currentClass?.name||'班级名称不匹配',type:'warning'});}catch{return;}await run(async()=>{const value=await auth.api.restoreBackup(workspace.classId,backupFile.value,mode.value);await workspace.reloadReferences();validated.value=false;return value;});}
async function clear(){try{await ElMessageBox.prompt(`输入“${workspace.currentClass?.name}”确认清空全部台账及学生数据。建议先下载备份。`,'清空班级数据',{type:'warning',inputValidator:value=>value===workspace.currentClass?.name||'班级名称不匹配'});}catch{return;}await run(async()=>{await auth.api.clearClassData(workspace.classId);await workspace.reloadReferences();return {message:'班级数据已清空'};});}
</script>
<template>
  <el-alert v-if="error" :title="error" type="error" :closable="false" />
  <section class="data-section"><h2>学生名册</h2><div class="business-toolbar"><el-button :disabled="busy" @click="run(async()=>downloadText(await auth.api.downloadStudents(workspace.classId),'students.csv','text/csv;charset=utf-8'))">导出学生 CSV</el-button><el-button @click="downloadText('\ufeffname,gender,contact\r\n','students-template.csv','text/csv;charset=utf-8')">下载导入模板</el-button></div><label class="file-label">CSV 文件<input type="file" accept=".csv,text/csv" :disabled="busy" @change="selectFile($event,'student')" /></label><div class="business-toolbar"><el-select v-model="strategy" aria-label="重复学生处理"><el-option value="skip" label="跳过重复学生"/><el-option value="create" label="仍然创建"/></el-select><el-button :disabled="!studentFile||busy" @click="importStudents(true)">预检查</el-button><el-button type="primary" :disabled="!studentFile||busy" @click="importStudents(false)">导入学生</el-button></div></section>
  <template v-if="!studentsOnly"><section class="data-section"><h2>旧版数据迁移</h2><label class="file-label">原生 JS 导出文件<input type="file" accept=".json" :disabled="busy" @change="chooseLegacy"/></label><div class="business-toolbar"><el-button :disabled="busy||!legacyFile" @click="migrate(true)">检查旧数据</el-button><el-button type="primary" :disabled="busy||!legacyChecked" @click="migrate(false)">迁入当前空班级</el-button></div></section><section class="data-section"><h2>班级备份</h2><el-button :disabled="busy" @click="run(async()=>downloadText(await auth.api.downloadBackup(workspace.classId),'teacher-logbook-backup.json'))">下载完整备份</el-button><label class="file-label">备份 JSON<input type="file" accept=".json,application/json" :disabled="busy" @change="selectFile($event,'backup')" /></label><div class="business-toolbar"><el-select v-model="mode" aria-label="恢复模式"><el-option value="merge" label="合并恢复"/><el-option value="replace" label="替换恢复"/></el-select><el-button :disabled="!backupFile||busy" @click="validate">校验备份</el-button><el-button type="primary" :disabled="!validated||busy" @click="restore">确认恢复</el-button></div></section><section class="data-section danger-zone"><h2>清空班级数据</h2><el-button type="danger" :disabled="busy" @click="clear">清空当前班级</el-button></section></template>
  <pre v-if="result" class="operation-result" role="status">{{ result }}</pre><p v-if="busy" role="status">正在处理文件</p>
</template>
