<script setup lang="ts">
import { ref } from 'vue';import { themes } from '@teacher-logbook/shared';import { api,state,loadWorkspace,selectClass,errorMessage,confirm } from '../lib/workspace';
defineProps<{mode:string}>();const name=ref('');const error=ref('');const busy=ref(false);
async function changeSkin(id:string){busy.value=true;try{await api.saveSkin(id);state.skin=id;}catch(cause){error.value=errorMessage(cause);}finally{busy.value=false;}}
async function create(){if(!name.value.trim()||busy.value)return;busy.value=true;try{const item=await api.createClass({name:name.value.trim(),timezone:'Asia/Shanghai'});name.value='';await loadWorkspace();await selectClass(item.id);}catch(cause){error.value=errorMessage(cause);}finally{busy.value=false;}}
async function rename(id:string,currentName:string){const result=await new Promise<UniApp.ShowModalRes>(resolve=>uni.showModal({title:'修改班级名称',editable:true,content:currentName,success:resolve}));if(!result.confirm||!result.content?.trim())return;busy.value=true;try{await api.renameClass(id,result.content.trim());await loadWorkspace();}catch(cause){error.value=errorMessage(cause);}finally{busy.value=false;}}
async function remove(id:string,currentName:string){if(!await confirm('删除班级',`确认删除“${currentName}”？该班级数据将无法继续访问。`))return;busy.value=true;try{await api.removeClass(id);await loadWorkspace();}catch(cause){error.value=errorMessage(cause);}finally{busy.value=false;}}
</script>
<template><view><text v-if="error" class="mini-error">{{ error }}</text><template v-if="mode==='settings'"><text class="mini-title">界面皮肤</text><button v-for="theme in themes" :key="theme.id" :disabled="busy" @click="changeSkin(theme.id)"><view class="mini-row"><view :style="{background:theme.sidebar,width:'40rpx',height:'40rpx'}"></view><view :style="{background:theme.brand,width:'40rpx',height:'40rpx'}"></view><text>{{ theme.name }}{{ state.skin===theme.id?' · 已使用':'' }}</text></view></button></template><template v-else><input v-model="name" placeholder="新班级名称"/><button class="primary" :loading="busy" @click="create">创建班级</button><view v-for="item in state.classes" :key="item.id" class="mini-record"><text class="mini-record-title">{{ item.name }}</text><view class="mini-row"><button size="mini" :disabled="busy" @click="selectClass(item.id)">{{ state.classId===item.id?'当前班级':'切换' }}</button><button size="mini" :disabled="busy" @click="rename(item.id,item.name)">重命名</button><button size="mini" :disabled="busy" @click="remove(item.id,item.name)">删除</button></view></view></template></view></template>
