<script setup lang="ts">
import { ref } from 'vue';import { api,state,references,errorMessage,confirm } from '../lib/workspace';import { chooseFile,shareText } from '../lib/files';
defineProps<{studentsOnly:boolean}>();const legacyFile=ref('');const legacyChecked=ref(false);
async function migrate(dryRun:boolean){if(!dryRun&&!await confirm('旧数据迁移','确认迁入当前空班级？'))return;await run(async()=>{const value=await api.importLegacy(state.classId,legacyFile.value,dryRun);legacyChecked.value=dryRun;if(!dryRun)await references();return value;});}
const busy=ref(false);const error=ref('');const result=ref('');const studentFile=ref('');const backupFile=ref('');const validated=ref(false);const replace=ref(false);
async function run(action:()=>Promise<unknown>){if(busy.value)return;busy.value=true;error.value='';result.value='';try{const value=await action();if(value!==undefined)result.value=JSON.stringify(value,null,2);}catch(cause){error.value=errorMessage(cause);}finally{busy.value=false;}}
async function importStudents(dryRun:boolean){await run(async()=>{const result=await api.uploadStudents(state.classId,studentFile.value,dryRun,'skip');if(!dryRun)await references();return result;});}
async function restore(){if(!await confirm('恢复备份',`确认${replace.value?'替换':'合并'}当前班级的数据？`))return;await run(async()=>{const value=await api.restoreBackup(state.classId,backupFile.value,replace.value?'replace':'merge');validated.value=false;await references();return value;});}
async function clear(){const name=state.classes.find(item=>item.id===state.classId)?.name;const answer=await new Promise<UniApp.ShowModalRes>(resolve=>uni.showModal({title:'清空班级数据',content:`请输入班级名称“${name}”确认`,editable:true,success:resolve}));if(!answer.confirm||answer.content!==name)return;await run(async()=>{await api.clearClassData(state.classId);await references();return {message:'已清空'};});}
</script>
<template><view><text v-if="error" class="mini-error">{{ error }}</text><view class="mini-section"><text class="mini-title">学生导入导出</text><button :disabled="busy" @click="run(async()=>shareText(await api.downloadStudents(state.classId),'students.csv'))">导出学生 CSV</button><button :disabled="busy" @click="run(async()=>{studentFile=await chooseFile('csv');return {message:'已选择 CSV'};})">选择 CSV 文件</button><view class="mini-row"><button :disabled="busy||!studentFile" @click="importStudents(true)">预检查</button><button class="primary" :disabled="busy||!studentFile" @click="importStudents(false)">导入学生</button></view></view><template v-if="!studentsOnly"><view class="mini-section"><text class="mini-title">旧版数据迁移</text><button :disabled="busy" @click="run(async()=>{legacyFile=await chooseFile('json');legacyChecked=false;return {message:'已选择旧版文件'};})">选择原版 JSON</button><button :disabled="busy||!legacyFile" @click="migrate(true)">检查旧数据</button><button class="primary" :disabled="busy||!legacyChecked" @click="migrate(false)">迁入当前空班级</button></view><view class="mini-section"><text class="mini-title">班级备份</text><button :disabled="busy" @click="run(async()=>shareText(await api.downloadBackup(state.classId),'teacher-logbook-backup.json'))">导出完整备份</button><button :disabled="busy" @click="run(async()=>{backupFile=await chooseFile('json');validated=false;return {message:'已选择备份'};})">选择备份 JSON</button><view class="mini-row"><text>替换恢复</text><switch :checked="replace" @change="replace=!replace"/></view><button :disabled="busy||!backupFile" @click="run(async()=>{const value=await api.validateBackup(state.classId,backupFile);validated=true;return value;})">校验备份</button><button class="primary" :disabled="busy||!validated" @click="restore">恢复备份</button></view><view class="mini-section"><button :disabled="busy" @click="clear">清空当前班级</button></view></template><text v-if="result" class="mini-result" selectable>{{ result }}</text><text v-if="busy">正在处理</text></view></template>
