<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';
import type { Dashboard } from '@teacher-logbook/api-client';
import { localDate } from '@teacher-logbook/shared';
import { api,state,studentName,errorMessage } from '../lib/workspace';
defineEmits<{open:[id:string]}>();const data=ref<Dashboard>();const error=ref('');const busy=ref(false);
const metrics=computed(()=>data.value?[['学生',data.value.studentSummary.total,'students'],['今日请假',data.value.leaveToday,'leave'],['未交人次',data.value.unsubmittedHomework,'homework'],['违纪',data.value.violationCount,'violations'],['本月工作',data.value.workRecordsThisMonth,'work'],['待办',data.value.pendingTodoCount,'todos']]:[]);
async function load(){busy.value=true;error.value='';try{data.value=await api.getDashboard(state.classId,localDate());}catch(cause){error.value=errorMessage(cause);}finally{busy.value=false;}}onMounted(load);
</script>
<template><view><button :loading="busy" @click="load">刷新总览</button><text v-if="error" class="mini-error">{{ error }}</text><view class="mini-row"><button v-for="action in [['leave','记请假'],['homework','记作业'],['violations','记违纪'],['work','记工作']]" :key="String(action[0])" size="mini" @click="$emit('open',action[0]!)">{{ action[1] }}</button></view><view class="mini-metrics"><view v-for="metric in metrics" :key="String(metric[0])" @click="$emit('open',String(metric[2]))"><text>{{ metric[0] }}</text><text class="mini-number">{{ metric[1] }}</text></view></view><template v-if="data"><view class="mini-section"><text class="mini-title">风险预警</text><view v-for="risk in [['情绪预警',data.alertSummary.emotion,'emotion'],['特殊体质',data.alertSummary.specialHealth,'health'],['辍学风险',data.alertSummary.dropoutRisk,'dropout'],['未返校',data.alertSummary.notReturned,'not-returned'],['待处理',data.alertSummary.pending,'alerts']]" :key="String(risk[0])" class="mini-detail" @click="$emit('open',String(risk[2]))"><text>{{ risk[0] }}</text><text>{{ risk[1] }}</text></view></view><view class="mini-section"><text class="mini-title">高风险学生</text><text v-if="!data.highRiskStudents.length" class="mini-caption">暂无提醒</text><view v-for="item in data.highRiskStudents" :key="item.id" class="mini-record" @click="$emit('open','alerts')">{{ studentName(item.studentId) }} · {{ item.type }}</view></view><view class="mini-section"><text class="mini-title">待跟进事项</text><text v-if="!data.upcomingTodos.length" class="mini-caption">暂无待办</text><view v-for="item in data.upcomingTodos" :key="item.id" class="mini-record" @click="$emit('open','todos')">{{ item.title }} · {{ item.due }}</view></view><view class="mini-section"><text class="mini-title">最近考试</text><text v-if="!data.latestExam" class="mini-caption">暂无考试</text><text v-else @click="$emit('open','exam-analysis')">{{ data.latestExam.name }} · {{ data.latestExam.subject }} · {{ data.latestExam.average }}</text></view><view class="mini-section"><text class="mini-title">近期工作</text><text v-if="!data.recentWorkRecords.length" class="mini-caption">暂无记录</text><view v-for="item in data.recentWorkRecords" :key="item.id" class="mini-record" @click="$emit('open','work')">{{ item.title }} · {{ item.date }}</view></view></template></view></template>
