<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';import type { SeatBoard } from '@teacher-logbook/api-client';import { api,state,studentName,errorMessage,confirm } from '../lib/workspace';
const board=ref<SeatBoard>();const selected=ref('');const error=ref('');const busy=ref(false);const settings=ref(false);const rows=ref('6');const columns=ref('2,2,2');
const unplaced=computed(()=>state.students.filter(student=>!board.value?.assignments.some(item=>item.studentId===student.id)));
const rowNumbers=computed(()=>Array.from({length:board.value?.layout.rows??0},(_,index)=>index+1));const columnNumbers=computed(()=>Array.from({length:board.value?.layout.columns??0},(_,index)=>index+1));
function assignment(row:number,column:number){return board.value?.assignments.find(item=>item.row===row&&item.column===column);}
async function load(){busy.value=true;error.value='';try{board.value=await api.getSeatBoard(state.classId);}catch(cause){error.value=errorMessage(cause);}finally{busy.value=false;}}
async function change(action:()=>Promise<unknown>){if(busy.value)return;busy.value=true;error.value='';try{await action();board.value=await api.getSeatBoard(state.classId);selected.value='';}catch(cause){error.value=errorMessage(cause);}finally{busy.value=false;}}
function choose(row:number,column:number){if(!board.value||busy.value)return;if(!selected.value){selected.value=assignment(row,column)?.studentId??'';return;}void change(()=>api.moveSeat(state.classId,board.value!.version,selected.value,row,column));}
async function clear(){if(await confirm('清空座位','所有学生将回到未安排列表，确认清空？'))await change(()=>api.removeSeat(state.classId,board.value!.version));}
async function saveLayout(){const groups=columns.value.split(/[,，\s]+/).filter(Boolean).map(Number);const total=groups.reduce((sum,size)=>sum+size,0);if(!Number.isInteger(Number(rows.value))||Number(rows.value)<1||Number(rows.value)>30||!groups.length||groups.some(size=>!Number.isInteger(size)||size<1||size>10)||total>30){error.value='行数 1–30，每组 1–10 列，总列数不超过 30';return;}const removed=board.value?.assignments.filter(item=>item.row>Number(rows.value)||item.column>total).length??0;if(removed&&!await confirm('调整布局',`${removed} 名学生将移回未安排列表，是否继续？`))return;await change(()=>api.saveSeatLayout(state.classId,board.value!.version,Number(rows.value),groups));if(!error.value)settings.value=false;}
onMounted(load);
</script>
<template><view><view class="mini-row"><button :loading="busy" @click="load">刷新</button><button :disabled="busy||!board" @click="rows=String(board!.layout.rows);columns=board!.layout.columnGroups.join(',');settings=true">布局设置</button><button :disabled="busy||!board" @click="clear">清空</button></view><text v-if="error" class="mini-error">{{ error }}</text><view v-if="board"><text class="mini-label">未安排学生 · {{ unplaced.length }}</text><scroll-view scroll-x class="mini-student-scroll"><button v-for="student in unplaced" :key="student.id" size="mini" :class="{primary:selected===student.id}" :disabled="busy" @click="selected=student.id">{{ student.name }} · {{ student.id.slice(0,4) }}</button></scroll-view><view v-if="selected" class="mini-row"><text>{{ studentName(selected) }}</text><button size="mini" @click="selected=''">取消选择</button><button v-if="board.assignments.some(item=>item.studentId===selected)" size="mini" :disabled="busy" @click="change(()=>api.removeSeat(state.classId,board!.version,selected))">移回未安排</button></view><scroll-view scroll-x scroll-y class="mini-seat-scroll"><view class="mini-podium">讲台</view><view v-for="row in rowNumbers" :key="row" class="mini-seat-row"><button v-for="column in columnNumbers" :key="column" :disabled="busy" :class="{primary:selected&&assignment(row,column)?.studentId===selected}" @click="choose(row,column)"><text>{{ row }}-{{ column }}</text><text>{{ assignment(row,column)?studentName(assignment(row,column)!.studentId):'空位' }}</text></button></view></scroll-view></view><view v-if="settings" class="mini-dialog"><text class="mini-title">座位布局</text><text class="mini-label">行数</text><input v-model="rows" type="number"/><text class="mini-label">各组列数</text><input v-model="columns" placeholder="2,2,2"/><text v-if="error" class="mini-error">{{ error }}</text><view class="mini-row"><button :disabled="busy" @click="settings=false">取消</button><button class="primary" :loading="busy" @click="saveLayout">保存</button></view></view></view></template>
