import { describe, expect, it, vi } from 'vitest';
import { createApi } from './index';
import type { Transport } from './index';
const row={id:'record-id',classId:'class-id',createdAt:'2026-09-09',updatedAt:'2026-09-09',title:'事项',status:'待完成'};
function setup(){const transport=vi.fn<Transport>();const api=createApi({baseUrl:'/api/v1',transport,getAccessToken:()=> 'fixture-access'});return{api,transport};}
describe('complete logbook API',()=>{
  it('uses compatible POST updates and authenticated resource scope',async()=>{const{api,transport}=setup();transport.mockResolvedValue({status:200,body:{code:200,data:row}});await api.saveRecord('class-id','todos',{status:'已完成'},'record-id');expect(transport.mock.calls[0]?.[0]).toMatchObject({method:'POST',url:'/api/v1/teacher-logbook/classes/class-id/todos/record-id',headers:{Authorization:'Bearer fixture-access'},body:{status:'已完成'}});});
  it('fetches all pages and rejects inconsistent exports',async()=>{const{api,transport}=setup();transport.mockResolvedValueOnce({status:200,body:{code:200,data:{items:[row],total:2,page:1,page_size:1,total_pages:2}}}).mockResolvedValueOnce({status:200,body:{code:200,data:{items:[{...row,id:'second'}],total:2,page:2,page_size:1,total_pages:2}}});expect(await api.allRecords('class-id','todos')).toHaveLength(2);expect(transport.mock.calls[1]?.[0].url).toContain('page=2');transport.mockResolvedValue({status:200,body:{code:200,data:{items:[row,row],total:2,page:1,page_size:2,total_pages:1}}});await expect(api.allRecords('class-id','todos')).rejects.toThrow('不一致');});
  it('carries If-Match for every seat change',async()=>{const{api,transport}=setup();transport.mockResolvedValue({status:200,body:{code:200,data:{version:3}}});await api.moveSeat('class-id',2,'student-id',1,2);expect(transport.mock.calls[0]?.[0]).toMatchObject({method:'PUT',headers:{'If-Match':'"seat-board-2"'},body:{row:1,column:2,swap:true}});await api.removeSeat('class-id',3);expect(transport.mock.calls[1]?.[0]).toMatchObject({method:'DELETE',headers:{'If-Match':'"seat-board-3"'}});});
  it('persists skin using the user preference API',async()=>{const{api,transport}=setup();transport.mockResolvedValue({status:200,body:{code:200,data:{skin:'apple'}}});expect(await api.getSkin()).toBe('apple');await api.saveSkin('mint');expect(transport.mock.calls[1]?.[0]).toMatchObject({method:'POST',body:{skin:'mint'}});});
  it('keeps file responses and multipart requests distinct from JSON',async()=>{const{api,transport}=setup();transport.mockResolvedValueOnce({status:200,body:'name,gender\r\n'});expect(await api.downloadStudents('class-id')).toBe('name,gender\r\n');expect(transport.mock.calls[0]?.[0].responseType).toBe('text');transport.mockResolvedValue({status:200,body:{code:200,data:{valid:true}}});await api.importLegacy('class-id','temporary-path',false);expect(transport.mock.calls[1]?.[0]).toMatchObject({method:'POST',upload:{file:'temporary-path',fields:{dryRun:'false',confirmation:'IMPORT_LEGACY_DATA'}}});});
  it('never retries or reports success on rejected mutations',async()=>{const{api,transport}=setup();transport.mockResolvedValue({status:412,body:{detail:{code:'VERSION_MISMATCH'}}});await expect(api.moveSeat('class-id',1,'student-id',1,1)).rejects.toMatchObject({status:412});expect(transport).toHaveBeenCalledOnce();});
});
